spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/movierecommender
    username: postgres
    password: cristian
    driver-class-name: org.postgresql.Driver